name = "Argz"
uuid = "41d54046-b03d-4046-bfed-09b63f41a8b6"
authors = ["Jorge Brito <jorge.brito.xyz@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
